# Generated by Django 5.0.1 on 2024-01-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de registro'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.CharField(max_length=50, verbose_name='Preço'),
        ),
    ]
