# Generated by Django 5.0.1 on 2024-01-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_venda_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='preco',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='venda_em',
            field=models.DateField(null=True),
        ),
    ]
