# Generated by Django 5.0.1 on 2024-02-01 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_rename_nome_produto_venda_cliente_and_more'),
    ]

    operations = [
    ]
