# Generated by Django 5.0.1 on 2024-02-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_auto_20240201_1635'),
    ]

    operations = [
    ]
