# Generated by Django 5.0.1 on 2024-02-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_venda_preco_alter_venda_cliente_alter_venda_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='preco',
            field=models.CharField(max_length=50),
        ),
    ]
