# Generated by Django 5.0.1 on 2024-02-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_alter_venda_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='preco',
            field=models.IntegerField(max_length=50),
        ),
    ]
