# Generated by Django 5.0.1 on 2024-02-12 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_alter_venda_preco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='preco',
        ),
    ]
