# Generated by Django 5.0.1 on 2024-02-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0008_remove_venda_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
