# Generated by Django 5.0.1 on 2024-01-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('nascimento', models.CharField(max_length=8)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=9)),
                ('endereco', models.CharField(max_length=50)),
                ('registrado_em', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
